name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Masuk ke direktori web atau clone jika belum ada
            mkdir -p /var/www
            cd /var/www
            if [ ! -d "portfolio-v2.0" ]; then
              echo "Direktori belum ada, melakukan git clone..."
              git clone https://github.com/0xriyans/portfolio-v2.0.git
            fi
            
            cd portfolio-v2.0
            
            # Tarik kode terbaru dari GitHub
            git checkout master
            git pull origin master
            
            # Update dependencies
            echo "Updating dependencies..."
            npm install --legacy-peer-deps
            
            # Build Gatsby site
            echo "Building static files..."
            npm run build
            
            # Jika menggunakan PM2 untuk serve (misal 'gatsby serve'), hapus komentar di bawah:
            # echo "Restarting PM2 services..."
            # pm2 restart portfolio
            # pm2 save
